spring:
  datasource:
    url: jdbc:postgresql1://localhost:5432/recipebook #java технологий которая позволяет программе общатся с базой данныз
    username: postgres
    password: postgres

  jpa: # библиотека котрая связывает базы данныз и йава классы
    hibernate: # реализует jpa
      ddl-auto: validate # создание таблиц, проверяет существует ли таблица
    show-sql: true

  liquibase:
    change-log: classpath:db\changelog/db.changelog-master.yaml
